name: Build - Action bundle
on:
  push:
    paths:
      - src/**
      - package-lock.json
      - tsconfig.json
      - test/**
    branches-ignore:
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    # Exclude in-repo PRs from running this job
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install npm development dependencies
        run: npm ci
      - name: Build action
        run: npm run build
      - name: Commit and push action bundle
        uses: EndBug/add-and-commit@cc9c08ba6c8df3b93a8f2db63e89b98368ae2ae8 # v11
        with:
          add: -f dist/main/index.js dist/cleanup_working_directory/index.js
          message: "chore(dist): build"
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
