name: Check format
on:
  push:
    paths:
      - src/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Node.JS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install NPM development dependencies
        run: npm install
      - name: Check format
        run: npm run format-check
